---

- name: Set Hostname
  action: hostname
    name='{{hn.stdout}}'

- name: fix hosts file
  action: lineinfile
    dest=/etc/hosts
    regexp='{{hn.stdout}}'
    line='127.0.0.1 {{hn.stdout}} {{hn.stdout}}.localdomain'
    state=present



