---

  - name: Set Hostname
    action: lineinfile
      dest=/etc/sysconfig/network
      regexp='HOSTNAME='
      line='HOSTNAME={{hn.stdout}}'
      state=present

  - name: Set Hostname on RHEL7+
    shell: echo {{hn.stdout}} > /etc/hostname
    when: ansible_distribution_major_version  > '6'


  - name: Set Hostname 3
    shell: hostname {{hn.stdout}}

  - name: fix hosts file
    action: lineinfile
      dest=/etc/hosts
      regexp='{{hn.stdout}}'
      line='127.0.0.1 {{hn.stdout}} {{hn.stdout}}.localdomain'
      state=present



