---
  - name: create LVs
    action: lvol
       vg={{ item.value.vg }}
       lv={{ item.value.lv }}
       size={{ item.value.size }}
       state=present 
    with_dict: "{{efin_app_disk}}"

  - name: create file systems
    action: filesystem
       fstype={{ item.value.fs }} 
       dev="/dev/{{ item.value.vg }}/{{ item.value.lv }}"
    with_dict: "{{efin_app_disk}}"

  - group_by: key={{ansible_system}}
  - debug: "msg=/dev/{{ item.value.vg }}/{{ item.value.lv }}  "
    with_dict: lvs
    
  - name: create mountpoints
    action: file 
      path={{item.value.mount}}
      state=directory
    with_dict: "{{efin_app_disk}}"

  - name: mount file systems
    action: mount
       fstype={{ item.value.fs }}
       src="/dev/{{ item.value.vg }}/{{ item.value.lv }}"
       state=mounted
       opts={{ item.value.opts }}
       name={{ item.value.mount }}
    with_dict: "{{efin_app_disk}}"


