---
- hosts: all

  tasks:
  - name: sudo checks - cp_admin
    action: lineinfile dest=/etc/sudoers.d/cp_admin regexp="^\W*%cp_admin" line="%cp_admin ALL=(root) /bin/su - efin,/bin/su - oracle,/bin/su - cp" state=present create=yes mode=0440
