---
- hosts: all
  vars_files:
  - ~/.userlist.yml
  gather_facts: no

  tasks:

  - name: Setup users groups
    action: group name={{item.key}} state=present
    with_dict: grps

  - name: work out home
    shell:  cd .. ;  pwd  
    register: hd

  - name: add user
    action: user name={{ item.value.name }} state=present group={{item.value.group}} append=yes password={{item.value.password}} groups={{item.value.groups}} comment="{{item.value.comment}}" home={{ hd.stdout }}/{{ item.value.name }} 
    with_dict: users
    ignore_errors: yes


  - name: create .ssh
    action: file path={{ hd.stdout }}/{{ item.value.name }}/.ssh state=directory owner={{ item.value.name }} mode=0700
    with_dict: users

 

  - name: push keys
    action: copy src=~/.ansible/tmp/{{ item.value.name }}.keys dest={{ hd.stdout }}/{{ item.value.name }}/.ssh/authorized_keys owner={{ item.value.name }} group={{item.value.group}} mode=0600
    with_dict: users

