---
- hosts: all
  vars:
     proxy: "{{ lookup('env','ANS_PROXY') }}"
     rs: "{{ lookup('env','RSYNC_PROXY') }}"


  tasks:
  - group_by: key={{ansible_system}}
  - debug: "msg={{ ansible_system }}"

  - name: fix anoying RH proxy rubbish
    action: lineinfile dest=/etc/yum.conf regexp='^proxy=' line='proxy=http://127.0.0.1:{{proxy}}' state=present


  - name: Put entry in hosts
    action: lineinfile dest=/etc/hosts regexp='^192.168.253.5 ntp' line='192.168.253.5 ntp'

  - name: install ntpd
    environment:
      http_proxy: http://127.0.0.1:{{proxy}}
    yum: name=ntp state=installed
    when: ansible_os_family == "RedHat"

  - name: get gateways  
    shell: netstat -rn | awk '$2 ~ /^[1-9]/ {print $2}' | sort -u
    register: gate

  - name: Find ntp.conf 
    shell: find /etc/ -type f -name ntp.conf
    register: ntp_loc

  - name: Clean raw ip MGMT box in ntp.conf  pt1
    action: lineinfile dest={{ntp_loc.stdout}} regexp='^server 192.168.253.5'  state=absent create=yes
  
  - name: Clean raw ip MGMT box in ntp.conf  pt2
    action: lineinfile dest={{ntp_loc.stdout}} regexp='^restrict 192.168.253.5' state=absent
 
  - name: PUT hosts in ntp.conf t1
    action: lineinfile dest={{ntp_loc.stdout}}  regexp='^restrict {{ item }}' line='restrict {{ item }}'
    with_flattened: 
      - gate.stdout_lines
      - ntp

  - name: PUT hosts in in ntp.conf  pt2
    action: lineinfile dest={{ntp_loc.stdout}}  regexp='^server {{item}}' line='server {{item}}' create=yes
    with_flattened: 
      - gate.stdout_lines
      - ntp

  - name: stop ntp service
    action: service name={{item}} state=stopped
    with_items:
      - ntp
      - ntpd
    ignore_errors: yes
  
  - name: do the ntpdate bit
    shell: /usr/sbin/ntpdate {{item}}
    with_flattened: 
      - gate.stdout_lines
      - ntp
    ignore_errors: yes

  - name: restart ntp service
    action: service name={{item}} state=restarted enabled=yes
    with_items:
      - ntp
      - ntpd
    ignore_errors: yes


