---
- hosts: all

  tasks:
  - name: sudo checks - e5_admin
    action: lineinfile dest=/etc/sudoers.d/e5_admin regexp="^\W*%e5_admin" line="%e5_admin ALL=(root) /bin/su - prod,/bin/su - test,/bin/su - devl,/bin/su - trng" state=present create=yes mode=0440
