---
- debug: msg="start of {{role_path|basename}} role"
  tags: always


- name: Get hostname mgmt
  local_action:
    shell grep -i {{ ansible_mgmt.ipv4.address }} /etc/hosts|  awk '{print $2}'
  when: ansible_mgmt.ipv4.address is defined
  register: hn
  sudo: no
  ignore_errors: True
  
- name: Get hostname build
  local_action:
    shell grep -i {{ ansible_build.ipv4.address }} /etc/hosts|  awk '{print $2}'
  when: ansible_build.ipv4.address is defined
  register: hn
  sudo: no
  ignore_errors: True

- include: linux.yml  
  when: "hn is defined and hn.rc == 0 and {{ansible_system}} | lower == 'linux'"

  

- set_fact: done_set_hostname=1



