---
  - debug: msg="start of {{role_path|basename}} role"
    tags: always

  - group_by: key={{ansible_system}}
  - debug: "msg={{ ansible_system }}"

  - include: {{ ansible_os_family }}

  - name: Put entry in hosts
    action: lineinfile dest=/etc/hosts regexp='^192.168.253.5 ntp' line='192.168.253.5 ntp'

  - name: get gateways  
    shell: netstat -rn | awk '$2 ~ /^[1-9]/ {print $2}' | sort -u
    register: gate

  - name: Find ntp.conf 
    shell: find /etc/ -type f -name ntp.conf
    register: ntp_loc

  - name: Clean raw ip MGMT box in ntp.conf  pt1
    action: lineinfile dest={{ntp_loc.stdout}} regexp='^server 192.168.253.5'  state=absent create=yes
  
  - name: Clean raw ip MGMT box in ntp.conf  pt2
    action: lineinfile dest={{ntp_loc.stdout}} regexp='^restrict 192.168.253.5' state=absent
 
  - name: PUT hosts in ntp.conf t1
    action: lineinfile dest={{ntp_loc.stdout}}  regexp='^restrict {{ item }}' line='restrict {{ item }}'
    with_flattened: 
      - gate.stdout_lines
      - ntp

  - name: PUT hosts in in ntp.conf  pt2
    action: lineinfile dest={{ntp_loc.stdout}}  regexp='^server {{item}}' line='server {{item}}' create=yes
    with_flattened: 
      - gate.stdout_lines
      - ntp

  - name: stop ntp service
    action: service name={{item}} state=stopped
    with_items:
      - ntp
    ignore_errors: yes
  
  - name: do the ntpdate bit
    shell: /usr/sbin/ntpdate {{item}}
    with_flattened: 
      - gate.stdout_lines
      - ntp
    ignore_errors: yes

  - name: restart ntp service
    action: service name={{item}} state=restarted enabled=yes
    with_items:
      - ntp
    ignore_errors: yes


