---
  - debug: msg="start of {{role_path|basename}} role"
    tags: always


# this is the generic zabbix stuff that needs to be done on all unix hosts
  - include: common.yml
    tags:
      - zabbix
      - zabbix-common


  - include: redhat.yml
    when: ansible_os_family | lower == 'redhat'
    tags:
      - zabbix
      - zabbix-rhel
      
  - include: debian.yml
    when: ansible_os_family | lower == 'debian'
    tags:
      - zabbix
      - zabbix-deb
