---
  - debug: msg="start of {{role_path|basename}} role"
    tags: always


  - name: tweak yum.conf
    action: lineinfile regexp="^proxy=http://127.0.0.1:{{proxy}}" line="proxy=http://127.0.0.1:{{proxy}}" dest=/etc/yum.conf state=present
    when: ansible_os_family | lower == 'redhat'
    tags: 
      - proxy
      - rhn_reg


  - name: fix rhn proxy
    action: lineinfile regexp="^httpProxy=http://127.0.0.1:{{proxy}}" line="httpProxy=http://127.0.0.1:{{proxy}}" dest=/etc/sysconfig/rhn/up2date state=present
    when: ansible_distribution | lower == 'redhat'
    tags:
      - proxy
      - rhn_reg

  - name: turn on rhn proxy
    action: lineinfile regexp="^enableProxy=0" line="enableProxy=1" dest=/etc/sysconfig/rhn/up2date state=present
    when: ansible_distribution | lower == 'redhat'
    tags:
      - proxy
      - rhn_reg

  - name: fix dodgy serverURL line
    action: lineinfile regexp="^(serverURL=.*)" line="#\1" dest=/etc/sysconfig/rhn/up2date state=present backrefs=yes
    when: ansible_distribution | lower == 'redhat'
    tags:
      - proxy
      - rhn_reg
      - rhn_url
    

