---
- hosts: all
  gather_facts: yes
  tasks:
    - name: get user passwd
      local_action: getent
        database=group
        key=uts
        split=","
    - debug: var=getent_group


    - name: Is user on this system?
      local_action: getent
        database=passwd
      no_log: True
    - debug: var=getent_passwd



    - name: print users
      action: shell
        "id {{ item}} "
      with_items: getent_group.name
        



