---
- hosts: all
  gather_facts: yes
  tasks:
    - debug: msg="System {{ ansible_os_family | lower }}"
      tags: always
    - group_by:
          key: "{{ansible_os_family | lower }}"
      tags: always
  # os agnostic roles
  roles:
    - blah
    - blah
    - blah





