---

##################################################
# this section is specific to RHEL systems and 
# installing the zabbix agents
# ################################################


  - name: remove old repo upload keys
    shell: rm -rf /var/tmp/pkg/*.rpm
      
  - name: stop zabbix and pre service agent
    action: service 
      name={{item}}
      state=stopped
      enabled=no
    ignore_errors: yes
    with_items:       
      - zabbix-prestart
      - zabbix-agent
  
  - name: remove agents
    action: yum 
      name={{ item }} 
      state=absent
      update_cache=yes
    with_items:
      - zabbix-sender
      - zabbix-get
      - zabbix-agent
      - zabbix-release
      - zabbix
    tags: zabbix-remove

  - name: remove zabbix files
    action: file
      name={{item}}
      state=absent
    items:
      - /etc/yum.repos.d/zabbix.repo
      - /etc/init.d/zabbix-agent


