---
  - debug: msg="start of {{role_path|basename}} role"
    tags: always

  - name: Setup users groups
    action: group name={{item.key}} state=present
    with_dict: grps
    tags: 
      - EFIN
      - EFIN-ADMIN

  - name: add user
    action: user name={{ item.value.name }} state=present append=yes password={{item.value.password}} update_password=on_create groups={{item.value.groups}} comment="{{item.value.comment}}"
    with_dict: users
    tags: 
      - EFIN
      - EFIN-ADMIN

  - name: push sudo file
    action: copy src=efin_admin dest=/etc/sudoers.d/efin_admin mode=0440 owner=root group=root backup=no
    tags: 
      - EFIN
      - EFIN-ADMIN

