---
- debug: msg="start of {{role_path|basename}} role"
  tags: always

- name: Assign NICS to firewalld zone
  action: firewalld
    port="{{item.port}}/{{item.prot}}"
    state=enabled
    permanent=true
    immediate=true
    zone=public
  with_items: "{{EFIN_ALL}} + {{EFIN_PROD}} + {{EFIN_TEST}} + {{EFIN_TRAIN}}"
  ignore_errors: yes
  when: ansible_distribution_major_version > "6"
  tags:
    - firewalld




