---

- name: generate passworld
  local_action: shell openssl rand -hex 32
  register: pass
  run_once: true

- name: push files
  action: template
    src={{item.s}} 
    dest="{{include_dir}}{{item.d}}"
    owner=zabbix 
    group=zabbix 
    mode=600
  with_items:
    - {s : "psk", d : "../zabbix_agentd.psk" }
    - {s : "tls.conf", d : "tls.conf"}
  when: ansible_distribution_major_version > "5"
  notify: restart_agent


- debug: msg=" psk is {{pass.stdout}} "
  run_once: true

