---
  - debug: msg="start of {{role_path|basename}} role"
    tags: always

  - block: # RHEL deived specif bits
    ######### RHEL tasks ########
    - name: turn off services not required for VM (mainly hardware daemons)
      action: service
        name={{item}}
        state=stopped
        enabled=no
      ignore_errors: yes
      # hack the red out
      failed_when: false
      when: ansible_virtualization_type|lower  ==  'vmware'
      tags:
        - services
      with_items:
        - cpuspeed
        - haldaemon
        - hidd
        - kudzu
        - microcode_ctl
        - readahead_early
        - readahead_later
        - smartd

    - name: turn off services not required
      action: service
        name={{item}}
        state=stopped
        enabled=no
      ignore_errors: yes
      tags:
        - services
      # hack the red out
      failed_when: false
      with_items:
        - mdmonitor
        - iptables
        - iptables6
        - xinetd
        - autofs
        - avahi-daemon
        - bluetooth
        - cups
        - gpm
        - iscsi
        - iscsid
        - isdn
        - mcstrans
        - messagebus
        - nfslock
        - portmap
        - rawdevices
        - restorecond
        - rpcgssd
        - rpcidmapd
        - sendmail
        - setroubleshoot
        - snmpd

    ######### end RHEL tasks ########
    when: ansible_os_family | lower == 'redhat'
    tags: 
      - disable_services_rhel
      - disable_services


  
