---
  - debug: msg="start of {{role_path|basename}} role"
    tags: always

  - name: make sure ssh tunneling allowed
    action: lineinfile
      dest=/etc/ssh/sshd_config
      regexp="^AllowTcpForwarding"
      line="AllowTcpForwarding yes"
      state=present
    notify: restart sshd
    tags: ssh_tunnel
