---
  - debug: msg="start of {{role_path|basename}} role"
    tags: always


  - include: setup-RedHat.yml
    when: " ansible_os_family | lower  == 'redhat' and {{done_static_routes|default(0)}} < 1"


