---

  - name: tweak exim start part1
    lineinfile: dest=/etc/sysconfig/exim regexp="^DAEMON=" line="DAEMON=yes" create=yes
  
  - name: tweak exim start part2
    lineinfile: dest=/etc/sysconfig/exim regexp="QUEUE=" line="QUEUE=5m" create=yes
    
  - name: install exim
    yum: name=exim state=present
  
  - name: push exim config
    copy: src=./exim.conf dest=/etc/exim/exim.conf backup=yes
  
  - name: destroy the evil sendmail
    yum: name=sendmail state=absent

  - name: WARNING IM DISBLING DNS
    shell: sed -e "s/^nameserver/#&/" -i /etc/resolv.conf

  - name: setup hosts
    lineinfile: dest=/etc/hosts regexp="mailer" line="172.25.97.18 eximmailer" create=yes

  - name: start exim forever
    service: name=exim state=started enabled=yes



