---
  - debug: msg="start of {{role_path|basename}} role"
    tags: always

  ### nested block for removal of GUI boot
  - block: # remove gui boot crap
    ### GUI TASKS ###
    - name: stop hiding the kernel init at boot grub defaults
      action: replace
        dest=/etc/default/grub
        regexp='(GRUB_CMDLINE_LINUX=.*)\s+(quiet|rhgb)(.+)(quiet|rhgb)(.+)'
        replace='\1 \3 \5'
        backup=yes

    - name: stop hiding the kernel init at boot grub config
      action: replace
        dest=/boot/grub2/grub.cfg
        regexp='(linux16 .*)\s+(quiet|rhgb)(.+)(quiet|rhgb)(.*)'
        replace='\1 \3 \5'
        backup=yes
    ### END GUI TASKS ###
    when: ansible_distribution_major_version > "6" and ansible_os_family | lower == 'redhat'
    tags:
      - gboot


