---
- hosts: all
  gather_facts: yes
  vars:
    os_type: RedHat
    proxy: "{{ lookup('env','ANS_PROXY') }}"
    rs: "{{ lookup('env','RSYNC_PROXY') }}"
  roles:
    - common

# these bits need to be included as playbook as we need to do specific things
# depending on os
- include: deploy_zabbix.yml
- include: RHEL.yml

