---
- hosts: all
  gather_facts: yes
  roles:
    - common
    - ora_pre
  tasks:
    - group_by:
          key: "{{ ansible_os_family | lower }}"


# these bits need to be included as playbook as we need to do specific things
# # depending on os
- include: deploy_zabbix.yml
- include: RHEL.yml

