---
  - name: Add repo keys
    action: copy src={{ item }} dest=/var/tmp/pkg/ mode=644 owner=root group=root
    with_fileglob:
      - repofiles/{{ansible_distribution_major_version}}/*.rpm
  
  - name: fix anoying RH proxy rubbish
    action: lineinfile dest=/etc/yum.conf regexp='^proxy=' line='proxy=http://127.0.0.1:{{proxy}}' state=present

  - name: Add repos
    action: yum name=/var/tmp/pkg/{{ item  | basename }} state=present disable_gpg_check=yes disablerepo="rhel*"
    with_fileglob:
      - repofiles/{{ansible_distribution_major_version}}/*.rpm
  
  - name: install agents
    action: yum name={{ item }} state=present disablerepo="rhel*,*Centos*,*epel*"
    environment:
      http_proxy: http://127.0.0.1:{{proxy}}
    with_items:
      - zabbix-sender
      - zabbix-get
      - zabbix-agent
    #  - facter

  - name: Mod systemd script if its present
    action: lineinfile dest=/usr/lib/systemd/system/zabbix-agent.service regexp='^ExecStart=/usr/sbin/zabbix_agentd$' line='ExecStart=. /etc/sysconfig/zabbix_agent; /usr/sbin/zabbix_agentd -c $CONFFILE'
    when: ansible_distribution_major_version > "6"

  - name: Fix sysconfig for RHEL7 derived distros
    when: ansible_distribution_major_version > "6"
    shell: mv /etc/sysconfig/zabbix-agent.7 /etc/sysconfig/zabbix-agent

  - name: Fix config for RHEL7 derived distros
    when: ansible_distribution_major_version > "6"
    action: lineinfile dest=/etc/zabbix/agentd.conf regexp='^PidFile=' line='PidFile=/run/zabbix/zabbix_agentd.pid' state=present




