---

# 1st pull in the correct disk layouts for the host

  - include_vars: oracle.yml
    when: "'Oracle' in group_names and {{ansible_distribution_major_version}} > 5"

  - include_vars: oracle_RHEL5.yml
    when: "'Oracle' in group_names and {{ansible_distribution_major_version}} < 6"

  - include_vars: efin_app_RHEL5.yml
    when: "'EFINAPP' in group_names and {{ansible_distribution_major_version}} < 6"
    
  - include_vars: efin_app.yml
    when: "'EFINAPP' in group_names and {{ansible_distribution_major_version}} > 5"


  - include_vars: e5_app.yml
    when: "'E5APP' in group_names"


