---


  - name: stop ntp service
    action: service name={{item}} state=stopped
    with_items:
      - ntp
    ignore_errors: yes
  
  - name: do the ntpdate bit
    shell: /usr/sbin/ntpdate {{item}}
    with_flattened: 
      - gate.stdout_lines
      - ntp
    ignore_errors: yes

  - name: restart ntp service
    action: service name={{item}} state=restarted enabled=yes
    with_items:
      - ntp
    ignore_errors: yes


