---

  - name: turn on proxy
    shell: "{{sub_comm}}"
    tags: rhn_prox

# RHEL 7 no longer supports RHN Classic subscription via rhn_register so subscription manager is used
  - name: Register & subscribe RHEL 
    action: redhat_subscription
     state=present 
     username=webabacus-webap-01 
     password=h0lycr4p! 
     autosubscribe=true
    environment:
      http_proxy: http://127.0.0.1:{{proxy}}
