---

##################################################
# this section is specific to RHEL systems and 
# installing the zabbix agents
# ################################################
  - debug: msg="sdfsdfsdf {{up_cache}}"

  - name: bouuf
    shell: "{{sub_comm}}"
    when: ansible_distribution | lower == "redhat"
    ignore_errors: yes

  - name: Add repo keys
    action: copy 
      src={{ item }} 
      dest=/var/tmp/pkg/ 
      mode=644 
      owner=root 
      group=root
    with_fileglob:
      - repofiles/{{ansible_distribution_major_version}}/*.rpm
  
  - name: fix anoying RH proxy rubbish
    action: lineinfile 
      dest=/etc/yum.conf 
      regexp='^proxy=' 
      line='proxy=http://127.0.0.1:{{proxy}}'   
      state=present

  - name: Add repos
    action: yum 
      name=/var/tmp/pkg/{{ item  | basename }} 
      state=present 
      disable_gpg_check=yes 
      disablerepo="rhel*"
    with_fileglob:
      - repofiles/{{ansible_distribution_major_version}}/*.rpm
  
  - name: install agents
    action: yum 
      name={{ item }} 
      state=latest 
      update_cache={{up_cache}}
      #disablerepo="rhel*,*Centos*,*epel*"
    environment:
      http_proxy: http://127.0.0.1:{{proxy}}
    with_items:
      - zabbix-sender
      - zabbix-get
      - zabbix-agent
    tags: zabbix-install

  - name: push agentd.conf
    action: template
      src=agentd.conf
      dest=/etc/zabbix/agentd.conf
      mode=644
      owner=root
      group=root

  - block:
    - name: fix firewall on RHEL7+
      action: service 
        name=firewalld 
        state=started 
        #enabled=yes 
      ignore_errors: yes
  
    - name: fix firewall on RHEL7+
      action: firewalld 
        permanent=yes 
        port=10050/tcp 
        state=enabled 
        immediate=yes
      ignore_errors: yes

    when: ansible_distribution_major_version > "6"

  - name: start zabbix and pre service agent
    action: service 
      name={{item}}
      state=restarted 
      enabled=yes
    with_items:       
      - zabbix-prestart
      - zabbix-agent
    tags: zabbix-start

