---
- hosts: all
  gather_facts: yes
  tasks:
    - debug: msg="System {{ ansible_os_family | lower }}"
      tags: always
    - group_by:
          key: "{{ansible_os_family | lower }}"
      tags: always


- hosts: redhat
  gather_facts: no
  vars:
    os_type: RedHat
    proxy: "{{ lookup('env','ANS_PROXY') }}"
    rs: "{{ lookup('env','RSYNC_PROXY') }}"

  roles:
     - zabbix


