---
- hosts: all

  tasks:
  - name: sudo checks - efin_admin
    action: lineinfile dest=/etc/sudoers.d/efin_admin regexp="^\W*%efin_admin" line="%efin_admin ALL=(root) /bin/su - efin,/bin/su - oracle,/bin/su - prod,/bin/su - test,/bin/su - devl,/bin/su - trng" state=present create=yes mode=0440
