---
- hosts: all
  gather_facts: yes
#  sudo: yes
  vars:
   os_type: RedHat
   proxy: "{{ lookup('env','ANS_PROXY') }}"
   rs: "{{ lookup('env','RSYNC_PROXY') }}"
                
  roles:
     - unix_users
     - ssh-harden



