---
- hosts: all
  gather_facts: yes
  tasks:
    - group_by:
          key: "{{ ansible_os_family | lower }}"


- hosts: redhat
  sudo: yes
  gather_facts: no
  vars:
    os_type: RedHat
  roles:
     - ntp

- hosts: debian
  sudo: yes
  gather_facts: no
  vars:
    os_type: Debian
  roles:
    - ntp


