---
- hosts: all
  gather_facts: no
  vars_files:
  - ~/.userlist.yml

  tasks:
  - name: Is user on this system?
    action: getent 
      database=passwd
    no_log: True

  - name: Reset Password - skips if user not already created
    action: user 
      name="{{ item.value.name }}" 
      state=present 
      password="{{item.value.password}}"
      update_password=always 
      comment="{{item.value.comment}}"
    with_dict: "{{users}}"
    when: item.value.name in getent_passwd

