---
- hosts: all
  gather_facts: no
  vars_files:
  - ~/.absinstaller.yml

  tasks:
  - name: reset absinstaller password
    action: user name={{ item.value.name }} state=present password={{item.value.password}} update_password=always
    with_dict: users

