---
- hosts: all
  gather_facts: yes
  tasks:
    - debug: msg="System {{ ansible_os_family | lower }}"
    - group_by:
          key: "ansible_os_family | lower "


- hosts: redhat
  sudo: yes
  gather_facts: no
  vars:
    os_type: RedHat
    proxy: "{{ lookup('env','ANS_PROXY') }}"
    rs: "{{ lookup('env','RSYNC_PROXY') }}"

  roles:
     - zabbix-redhat

- hosts: debian
  sudo: yes
  gather_facts: no
  vars:
    proxy: "{{ lookup('env','ANS_PROXY') }}"
    rs: "{{ lookup('env','RSYNC_PROXY') }}"
    os_type: Debian
  roles:
    - zabbix-debian


- hosts: all
  gather_facts: yes
  tasks:
    - debug: msg="System {{ ansible_os_family | lower }}"
  roles:
    - zabbix

