---
  - debug: msg="start of {{role_path|basename}} role"
    tags: always

  - name: make tmpdir
    action: file 
      path=/var/tmp/pkg 
      state=directory 
      owner=root 
      mode=0755
    tags:
      - zabbix
      - zabbix-common
  
  - name: put zabbix entries in hosts
    action: lineinfile 
      dest=/etc/hosts 
      regexp='^192.168.253.5\W*{{item}}$' 
      line="192.168.253.5 {{item}}"  
      state=present
    with_items:
      - zabbix_server
      - zabbix_server2
      - zabbix_active_server
    tags:
      - zabbix
      - zabbix-common

#  - include: ./{{os_type}}.yml

#  - name: pull zabbix config
#    action: command /usr/bin/rsync --port={{ rs }} -aP 127.0.0.1::zabbix/linux/{{item}}/ /{{item}}/ 
#    with_items:
#      - opt
#      - etc
#
#       

  - name: add zabbix group
    action: group name=zabbix state=present
    tags:
      - zabbix
  
  - name: add zabbix user
    action: user 
      name=zabbix 
      group=zabbix 
      comment="zabbix agent account" 
      shell=/sbin/nologinc
    tags:
      - zabbix

  - name: Push zabbix Config
    action: copy 
      src={{item.value.src}} 
      dest={{item.value.dst}} 
      owner=root
      group=zabbix 
      mode=750
      directory_mode=750
    with_dict: zabbix_files
    tags:
      - zabbix
      - zabbix-common

  - name: sudo checks - zabbix
    action: lineinfile 
      dest=/etc/sudoers 
      regexp='^zabbix ALL' 
      line='zabbix ALL=(ALL) NOPASSWD:ALL'  
      state=present 
      create=yes 
      mode=0440
    tags:
      - zabbix
      - zabbix-common

  - name: sudo checks - zabbix
    action: lineinfile 
      dest=/etc/sudoers 
      regexp='^zabbix !requiretty' 
      line='Defaults:zabbix !requiretty'  
      state=present 
      create=yes 
      mode=0440
    tags:
      - zabbix
      - zabbix-common


